ci: 测试cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,9 +45,61 @@ jobs:
 
         flutter build macos --release --no-tree-shake-icons
 
-        # 将/build/macos/Build/Products/Release/目录下的文件复制到dist目录下
-        # cp -r build/macos/Build/Products/Release/* dist/
-        cp -r build/macos/Build/Products/Release/*.app dist/
+        # 确定输出目录
+        OUTPUT_DIR="$PROJECT_DIR/build/macos/Build/Products/Release"
+
+        # 创建临时目录
+        DMG_DIR="$OUTPUT_DIR/dmg_temp"
+        if [[ -d $DMG_DIR ]]; then
+            rm -rf "${DMG_DIR:?}/"*
+        else
+            mkdir -p "$DMG_DIR"
+        fi
+
+        # 获取应用程序名称
+        APP_NAME=$(echo $OUTPUT_DIR/*.app | awk -F 'Release/' '{print $2}' | awk -F .app '{print $1}')
+
+        # 获取当前时间
+        CURRENT_TIME=$(date "+%Y%m%d_%H%M")
+
+        # 确定DMG名称
+        DMG_NAME="${APP_NAME}_${CURRENT_TIME}.dmg"
+
+        # 应用签名
+        codesign -f -o runtime -s ${{secrets.IDENTITY_NAME}} -v "${OUTPUT_DIR}/${APP_NAME}.app" --deep
+
+        # 生成钥匙串密码凭证
+        xcrun notarytool store-credentials 'pictorial' --apple-id ${{secrets.USER_NAME}} --team-id ${{secrets.TEAM_ID}} --passwrod ${{secrets.ACCOUNT_PASSWORD}}
+
+        # 将应用程序复制到临时目录
+        cp -R "$OUTPUT_DIR/$APP_NAME.app" "$DMG_DIR" || exit 1
+
+        # 确定DMG路径
+        DMG_PATH="$OUTPUT_DIR/$DMG_NAME"
+
+        # 创建DMG文件
+        hdiutil create -volname 'Pictorial' -srcfolder "$DMG_DIR" -ov -format UDZO "$DMG_PATH"
+
+        # 提交到公证服务
+        xcrun notarytool submit "$DMG_PATH" --keychain-profile "pictorial" --wait --no-s3-acceleration
+
+        # 注入公证信息
+        xcrun stapler staple "$DMG_PATH"
+
+        # 删除临时目录
+        rm -rf "$DMG_DIR"
+
+        # 检查DMG是否创建成功
+        if [ -f "$DMG_PATH" ]; then
+            # 将/build/macos/Build/Products/Release/目录下的文件复制到dist目录下
+            cp -r "$DMG_PATH" dist/
+        else
+            echo "Failed to create DMG"
+            exit 1
+        fi
+
+        # 删除构建产物
+        # rm -rf "$OUTPUT_DIR"
 
         # echo "Build artifact 1" > dist/artifact1.txt  # 模拟构建产物
         # echo "Build artifact 2" > dist/artifact2.txt  # 模拟构建产物
